version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Password123
      - DB_NAME=your_database
      - DB_PORT=1433
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=admin
      - MSSQL_PID=Express
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mssql-data:
    driver: local